services:
  assethub:
    container_name: assethub
    build:
      context: .
      dockerfile: ./Dockerfile
      target: assethub
    environment:
      - PORT=8822
    ports:
      - "8822:8822"
    restart: always
